
name: Deploy Cloud Function

env:
  PROJECT: united-axle-390115

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: deploy cloud function
      id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: extract_game_data
        region: europe-west2
        runtime: python39
        memory_mb: '256'
        project_id:  ${{env.PROJECT}}
        entry_point: extract_game_data
        timeout: 300
        min_instances: 0
        max_instances: 1

