
name: Deploy Cloud Function

env:
  PROJECT: united-axle-390115
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        create_credentials_file: 'true'
        workload_identity_provider: 'projects/561310818303/locations/global/workloadIdentityPools/my-pool/providers/chess-app-provider'
        service_account: 'app-engine@united-axle-390115.iam.gserviceaccount.com'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list

    - name: deploy cloud function
      id: deploy
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: extract_game_data
        region: europe-west2
        runtime: python39
        memory_mb: '256'
        project_id:  ${{env.PROJECT}}
        entry_point: functions.extract_game_data