
name: Deploy Cloud Function

env:
  PROJECT: united-axle-390115

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mark as a success
      run: exit 0

  Deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: 'actions/checkout@v3'

    - id: Authenticate-GCP
      if: github.ref == 'refs/heads/master'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: Deploy-GCP
      if: github.ref == 'refs/heads/master'
      uses: google-github-actions/deploy-cloud-functions@main
      with:
        name: extract_game_data
        region: europe-west2
        runtime: python39
        memory_mb: 256
        project_id:  ${{env.PROJECT}}
        entry_point: extract_game_data
        timeout: 300
        min_instances: 0
        max_instances: 1

